version: '3.8'
services:
    server:
        container_name: backend
        image: skellord/tww:backend
        build: ./
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MONGO_URI=mongodb://host.docker.internal:27017/tww?retryWrites=true
        ports:
            - '5000:5000'
